👷 Update GitHub Actions to use GitFlow
IslasGECI/common_task_framework pull request #3
Opened 2022-02-04 22:01 UTC by devarops

2022-02-08 18:59 UTC, islasfernando requested changes

2022-02-08 18:59 UTC, islasfernando commented on .github/workflows/develop.yml
> +    - name: Corre pruebas y evalúa cobertura
Me confirman porfavor, creo que en este repo no hay para checar cobertura

2022-02-08 18:59 UTC, islasfernando commented on .github/workflows/main.yml
> +    - name: Corre pruebas y evalúa cobertura
No hay para checar cobertura todavía.

```suggestion
    - name: Corre pruebas
```

2022-02-08 19:03 UTC, devarops commented
Muchas gracias, @islasfernando, por tu amable revisión. En un momento lo atiendo.
Gracias.

2022-02-14 03:50 UTC, devarops commented
Tenías razón @islasfernando . Ya lo corregí.

2022-02-14 21:16 UTC, islasfernando approved these changes
LGTM

2022-02-14 21:16 UTC, merged